In [1]:
True + 4


5

In [2]:
text = 'hello'

print(text[4:100])


o


In [13]:
def almost_double_factorial(n):
    if n == 0:
        return 1
    res = 1
    right = n + 1
    if n % 2 == 0:
        n +=1
    for i in range(1, right, 2):
        res *= i
        print(i, res)
    return res


print(almost_double_factorial(20))


1 1
3 3
5 15
7 105
9 945
11 10395
13 135135
15 2027025
17 34459425
19 654729075
654729075


In [18]:

items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

#print(items[1][1])

sorted_items = sorted(items, key=lambda x: x[1][-1])

print(items)
print(sorted_items)
#sorted_items = [ ('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six'),]

[('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]
[('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]


In [20]:
x = [1, 2, 3, 4, 5]
x[::-2] = [-1, -3, -5]
#[-5, 2, -3, 4, -1]
print(x)

[-5, 2, -3, 4, -1]


In [50]:
def cumsum_and_erase(A, erase = None):
    for i in range(1, len(A)):
        A[i] = A[i] + A[i - 1]
    print(A)
    B = list(filter(lambda x: x != erase, A))
    return B

#A = [5, 1, 4, 5, 14] 
#A = [10] 
A = [5, 1, 4, 0, 5, -5,  19]
B = cumsum_and_erase(A, erase=10) 
print(B)
assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

[5, 6, 10, 10, 15, 10, 29]
[5, 6, 15, 29]


In [73]:

def process(sentences):
    for i in range(0, len(sentences)):
        sentences[i] = [x for x in sentences[i].split(' ') if x.isalpha()]

    result = [' '.join(x) for x in sentences]
    return result

print( process(['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100', '888']))
#['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100', '888']
#['thousand devils', 'My name is', 'Room costs', '']


['thousand devils', 'My name is', 'Room costs', '']


In [63]:
print('a12'.isalpha())

False


In [78]:
from functools import reduce

a = reduce(lambda x,y: x+y ,[x1*x2 for x1,x2 in zip([1,2,3], [1, 2, 3])])
print(a)

14


In [81]:
class Neuron:

    def __init__(self, w, f = lambda x: x):
        self.weight = w
        self.func = f
        self.last = None

    def forward(self, x):
        self.last = x
        return self.func(reduce(lambda x,y: x+y ,[x1*x2 for x1,x2 in zip(self.last, self.weight)]))

    def backlog(self):
        return self.last
    
n = Neuron([1,2,3])
print(n.forward([1,2,3]))
print(n.backlog())

14
[1, 2, 3]


In [85]:
import numpy as np

a = np.array([[5, 1, -2, 0],[0, 3, 4, 3],[2, 3, 1, 1]])
b = np.array([[1, -3],[2, -2],[3, -1],[0, 0]])
c = a@b
print( np.sum(c, axis = (0,1)))

-8


In [137]:
a = [1,2,3,4,5,6,7]
print(a[0:1])

[1]


In [168]:
a = [[1, 2],[3, 4]]
b = [[1, 2],[3, 4]]
for i_1,i_2 in zip([k for k in range(len(a[0]))], [m for m in range(len(b))]):
    print(i_1,i_2)
    
s = [a[0][i_1]*b[i_2][0] for i_1,i_2 in zip([k for k in range(len(a[0]))], [m for m in range(len(b))])]
print(s)

0 0
1 1
[1, 6]


In [174]:
import numpy as np

def no_numpy_mult(first, second):
    result = [[0 for j in range(len(second[0]))] for i in range(len(first))]
    #print(result, len(first),len(second[0]))
    for i in range(len(first)):
        for j in range(len(second[0])):
           # print(i,j)
            result[i][j] = sum(first[i][k]*second[m][j] for k,m in zip([k_1 for k_1 in range(len(first[0]))], [m_1 for m_1 in range(len(second))]))
    return result

def numpy_mult(first, second):
    result = first @ second
   #print(first,'_\n', second,'_\n', result)
    return result

a = [[1, 2],[3, 4]]
b = [[1, 2],[3, 4]]
print('no',no_numpy_mult(a,b))

a_ = np.array([[1, 2],[3, 4]])
b_ = np.array([[1, 2],[3, 4]])
print('yes',numpy_mult(a_,b_))

no [[7, 10], [15, 22]]
yes [[ 7 10]
 [15 22]]


In [177]:
import numpy as np

def no_numpy_scalar(v1, v2):
    result = sum(v1[i]*v2[j] for i,j in zip(range(len(v1)),range(len(v2))))
    return result

def numpy_scalar (v1, v2):
    result = np.sum(v1*v2)
    return result

v1_ = [1, 2, 3]
v2_ = [1, 2, 3]
print(no_numpy_scalar(v1_, v2_))

v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
print(numpy_scalar(v1, v2))


14
14


In [180]:
import numpy as np #не стирать!        

def diag_2k(a):
    result = np.sum(x for x in np.diagonal(a) if x % 2 == 0)
    return result

a = np.array([[1,0],[3,6]])
print(diag_2k(a))

6


<ipython-input-180-f5e9ce880ba5>:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  result = np.sum(x for x in np.diagonal(a) if x % 2 == 0)


In [181]:
import numpy as np

def cumsum(A):
    return A.cumsum(axis = 1)

a = np.array([[1,2], [3,4]])
print(cumsum(a))

[[1 3]
 [3 7]]


6.1 Склеивание

In [21]:
import numpy as np

def transform(X, a=1):
    Y = X.copy()
    Y[:,1::2] = a
    Y[:, ::2] = Y[:, ::2]**3
    return np.concatenate((X, Y[:,::-1]), axis = 1)

x = np.array([[100,200,300,400,500]])
print(transform(x),x)

[[      100       200       300       400       500 125000000         1
   27000000         1   1000000]] [[100 200 300 400 500]]


In [42]:
import numpy as np


x = np.array([[100,200,300,400,500],[100,200,300,400,500]])
print(x)
print(x[:,::2])
b = x.copy()
b[:,::2] = 1
b[:, 1::2] = b[:, 1::2]**2
print('b\n',b,'x\n',x)
c = np.concatenate((b,x), axis = 1)
print(c)

[[100 200 300 400 500]
 [100 200 300 400 500]]
[[100 300 500]
 [100 300 500]]
b
 [[     1  40000      1 160000      1]
 [     1  40000      1 160000      1]] x
 [[100 200 300 400 500]
 [100 200 300 400 500]]
[[     1  40000      1 160000      1    100    200    300    400    500]
 [     1  40000      1 160000      1    100    200    300    400    500]]


In [46]:
import numpy as np

def encode(a):
    non_zero = np.nonzero(np.diff(a))
    elems = np.append(x[non_zero],x[-1])
    poses = np.diff(np.append(np.insert(non_zero,0,-1), (len(x) -1) ))
    return (elems,poses)

x = np.array([0, 0, 1, 2, 3, 3, 7, 7, 9])
print(encode(x))

(array([0, 1, 2, 3, 7, 9]), array([2, 1, 1, 2, 2, 1], dtype=int64))


In [45]:
x = np.array([0, 0, 1, 2, 3, 3, 7, 7, 9])
print(np.diff(x))
a = np.nonzero(np.diff(x))
elems = np.append(x[np.nonzero(np.diff(x))],x[-1])
a = np.append(np.insert(a,0,-1), (len(x) -1) )
print('a', a)
print(elems)
print(np.diff(a))

[0 1 1 1 0 4 0 2]
a [-1  1  2  3  5  7  8]
[0 1 2 3 7 9]
[2 1 1 2 2 1]
