In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('data.txt', delimiter = ',', index_col = 0)

In [4]:
data.head()

X   Y  Cluster
Object                 
1       18  11        0
2       13  16        1
3       16  12        2
4       19   5        0
5       20  19        0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 1 to 15
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   X        15 non-null     int64
 1   Y        15 non-null     int64
 2   Cluster  15 non-null     int64
dtypes: int64(3)
memory usage: 480.0 bytes


In [6]:
x = pd.DataFrame(data.iloc[:, :2])
print(x)

         X   Y
Object        
1       18  11
2       13  16
3       16  12
4       19   5
5       20  19
6       17   1
7        3   1
8       15  18
9        6   4
10      11   4
11       5  16
12      19  11
13       5  12
14      10  11
15       9   2


In [7]:
from sklearn.cluster import KMeans
import numpy as np

In [8]:
result = KMeans(n_clusters=3, init=np.array([[15.0, 8.5], [9.0, 12.83], [14.0, 5.0]]), max_iter=100, n_init=1).fit(x)

In [9]:
print(result.predict(x))

[0 1 0 0 0 2 2 0 2 2 1 0 1 1 2]


In [10]:
centroid0 = result.cluster_centers_[0]
result.cluster_centers_

array([[17.83333333, 12.66666667],
       [ 8.25      , 13.75      ],
       [ 9.2       ,  2.4       ]])

In [11]:
coords = x.iloc[[0,2,3,4,7,11]].to_numpy()
coords.shape
coords

array([[18, 11],
       [16, 12],
       [19,  5],
       [20, 19],
       [15, 18],
       [19, 11]], dtype=int64)

In [12]:
from scipy.spatial.distance import euclidean

In [13]:
centr = coords.sum(axis = 0)/coords.size
centr

array([8.91666667, 6.33333333])

In [14]:
res = np.array([np.sqrt(((obj-centr)**2).sum()) for obj in coords]).sum()/coords.size
print(res)

5.8794627605977725


In [15]:
#5.880 2.179 

In [16]:
euclidean(np.array([2,2]), np.array([3,3]))

1.4142135623730951

In [17]:
np.sqrt(((np.array([2,2]) - np.array([3,3]))**2).sum())
x

X   Y
Object        
1       18  11
2       13  16
3       16  12
4       19   5
5       20  19
6       17   1
7        3   1
8       15  18
9        6   4
10      11   4
11       5  16
12      19  11
13       5  12
14      10  11
15       9   2

In [40]:
alldistances = result.fit_transform(x)
print(alldistances[: , :1].sum()/alldistances.size)
alldistances

3.0279869298380593


array([[ 1.67497927, 10.13039979, 12.30447073],
       [ 5.87130498,  5.25594901, 14.12090649],
       [ 1.95078332,  7.94512429, 11.76435294],
       [ 7.75492675, 13.86091628, 10.13903348],
       [ 6.69369521, 12.86953768, 19.80403999],
       [11.69639071, 15.46366709,  7.9246451 ],
       [18.87164245, 13.78858223,  6.35609943],
       [ 6.03922364,  7.97652807, 16.64331698],
       [14.66761361, 10.00624805,  3.57770876],
       [11.03655542, 10.13039979,  2.40831892],
       [13.25916874,  3.95284708, 14.23376268],
       [ 2.03442594, 11.09617051, 13.03840481],
       [12.85063768,  3.69120577, 10.47854952],
       [ 8.00867585,  3.2596012 ,  8.63712915],
       [13.84938827, 11.77391184,  0.4472136 ]])

In [42]:
slice = [0,2,3,4,7,11]
alldistances[: , :1][slice].sum()/len(slice)

4.358005687892644